# Cozy for Alacritty
# ~/.config/alacritty/theme.toml

[colors.cursor]
cursor = "#d5d6c8"
text = "#202729"

[colors.footer_bar]
background = "#e6e6de"
foreground = "#1c2225"

[colors.hints.end]
background = "#1c2225"
foreground = "#d5d6c8"

[colors.hints.start]
background = "#d5d6c8"
foreground = "#1c2225"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.bright]
black = "#636869"
blue = "#9bb7df"
cyan = "#a9d4b4"
green = "#c1d4a5"
magenta = "#e9b9da"
red = "#eb9899"
white = "#aaaba0"
yellow = "#e2c999"

[colors.normal]
black = "#636869"
blue = "#82a5d7"
cyan = "#93c9a1"
green = "#b2c98f"
magenta = "#e3a8d1"
red = "#e67e80"
white = "#d5d6c8"
yellow = "#dbbc7f"

[colors.primary]
background = "#202729"
bright_foreground = "#aaaba0"
dim_foreground = "#e6e6de"
foreground = "#d5d6c8"

[colors.search.focused_match]
background = "#b2c98f"
foreground = "#202729"

[colors.search.matches]
background = "#82a5d7"
foreground = "#202729"

[colors.selection]
background = "#232b2e"
text = "#d5d6c8"

[colors.vi_mode_cursor]
cursor = "#d5d6c8"
text = "#202729"
    