# Interstellar for Alacritty
# ~/.config/alacritty/theme.toml

[colors.cursor]
cursor = "#bfc0c2"
text = "#1c1f24"

[colors.footer_bar]
background = "#eaeaeb"
foreground = "#14161a"

[colors.hints.end]
background = "#14161a"
foreground = "#bfc0c2"

[colors.hints.start]
background = "#bfc0c2"
foreground = "#14161a"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.bright]
black = "#696b71"
blue = "#81bff2"
cyan = "#84d7c3"
green = "#adcf94"
magenta = "#e493c2"
red = "#e68991"
white = "#a9abae"
yellow = "#eacd95"

[colors.normal]
black = "#696b71"
blue = "#61afef"
cyan = "#65cdb4"
green = "#98c379"
magenta = "#dd78b3"
red = "#e06c75"
white = "#bfc0c2"
yellow = "#e5c07b"

[colors.primary]
background = "#1c1f24"
bright_foreground = "#a9abae"
dim_foreground = "#eaeaeb"
foreground = "#bfc0c2"

[colors.search.focused_match]
background = "#98c379"
foreground = "#1c1f24"

[colors.search.matches]
background = "#61afef"
foreground = "#1c1f24"

[colors.selection]
background = "#282c34"
text = "#bfc0c2"

[colors.vi_mode_cursor]
cursor = "#bfc0c2"
text = "#1c1f24"
    