# Galax for Alacritty
# ~/.config/alacritty/theme.toml

[colors.cursor]
cursor = "#dcdac9"
text = "#181820"

[colors.footer_bar]
background = "#c8c4aa"
foreground = "#16161d"

[colors.hints.end]
background = "#16161d"
foreground = "#dcdac9"

[colors.hints.start]
background = "#dcdac9"
foreground = "#16161d"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.bright]
black = "#9a9991"
blue = "#92abde"
cyan = "#89bfaa"
green = "#c2dd96"
magenta = "#da97ad"
red = "#e8808b"
white = "#dedccd"
yellow = "#ebce9c"

[colors.normal]
black = "#686760"
blue = "#7e9cd8"
cyan = "#6caf95"
green = "#b3d57d"
magenta = "#d27e99"
red = "#e46876"
white = "#dcdac9"
yellow = "#e6c384"

[colors.primary]
background = "#16161d"
bright_foreground = "#dedccd"
dim_foreground = "#c8c4aa"
foreground = "#dcdac9"

[colors.search.focused_match]
background = "#b3d57d"
foreground = "#181820"

[colors.search.matches]
background = "#7e9cd8"
foreground = "#181820"

[colors.selection]
background = "#1a1a22"
text = "#dcdac9"

[colors.vi_mode_cursor]
cursor = "#dcdac9"
text = "#181820"
    