# Cozy for Alacritty
# ~/.config/alacritty/theme.toml

[colors.cursor]
cursor = "#ebdbb2"
text = "#282828"

[colors.footer_bar]
background = "#fbf1c7"
foreground = "#21201f"

[colors.hints.end]
background = "#21201f"
foreground = "#ebdbb2"

[colors.hints.start]
background = "#ebdbb2"
foreground = "#21201f"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.bright]
black = "#665c54"
blue = "#95b3cf"
cyan = "#95cfad"
green = "#c7c96e"
magenta = "#dc9eaf"
red = "#f08c8c"
white = "#d5c4a1"
yellow = "#fbca59"

[colors.normal]
black = "#665c54"
blue = "#7ba0c3"
cyan = "#7bc398"
green = "#b9bb4a"
magenta = "#d3869b"
red = "#ec6f6f"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.primary]
background = "#282828"
bright_foreground = "#d5c4a1"
dim_foreground = "#fbf1c7"
foreground = "#ebdbb2"

[colors.search.focused_match]
background = "#ebdbb2"
foreground = "#282828"

[colors.search.matches]
background = "#7ba0c3"
foreground = "#282828"

[colors.selection]
background = "#32302f"
text = "#ebdbb2"

[colors.vi_mode_cursor]
cursor = "#ebdbb2"
text = "#282828"
    