[buildPlans.Astro]
family = "Astro"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Astro.variants]
inherits = "ss14"

[buildPlans.Astro.variants.design]
seven = "straight-serifless"
zero = "slashed"
capital-i = "serifed"
u = "toothed-serifless"
paren = "normal"
at = "compact"

[buildPlans.Astro.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Astro.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Astro.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Astro.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Astro.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.Astro.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.Astro.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Astro.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Astro.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
